name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MinGW and CMake
        run: |
          choco install mingw -y
          choco install cmake -y
          echo "C:\ProgramData\chocolatey\bin" >> $env:GITHUB_PATH

      - name: Prepare directories
        run: |
          mkdir -p lib

      - name: Build with MinGW
        run: |
          make BUILD_OPENCL=1 CC=gcc
