name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # استفاده از ماشین مجازی ویندوز

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MinGW
        run: |
          choco install mingw -y
          echo "C:\ProgramData\chocolatey\bin" >> $env:GITHUB_PATH

      - name: Build with MinGW
        run: |
          make BUILD_OPENCL=1 CC=gcc
